version: "3.9"
services:
  discovery:
    build: ../EuerkaServerProject
    ports:
      - "8761:8761"
    image: "discovery-service"
  candidat:
    build: ../Candidate
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3000:8080"
    image: "candidate-service"
    depends_on:
      - discovery
  job_A:
    build: ../JobAppNour/JobApp
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8180:8180"
    image: "job-service"